### ISSUE TITLE
Mouse zoom doesn't preserve marker location

### ISSUE THREAD

**Issue by elvisef** [hosuaby/Leaflet.SmoothMarkerBouncing#24] opened 2020-01-27 14:04 UTC
While zooming, only one marker is still in place, other markers change locations.
![Zaznaczenie_271](https://user-images.githubusercontent.com/25976749/73180799-589d2100-4116-11ea-95fe-c7fb9ab00913.png)
![Zaznaczenie_272](https://user-images.githubusercontent.com/25976749/73181099-e5e07580-4116-11ea-9499-3fa2f47a1a46.png)

I fixed this here (commented out code):

`    L.Marker.prototype._setPos = function(pos) {
        oldSetPos.call(this, pos);
        // if(this._bouncingMotion === undefined) {
        //     this._bouncingMotion = {};
        // }
        this._bouncingMotion.x = pos.x;
        this._bouncingMotion.y = pos.y;
        this._calculateTransforms();
    };`

Please take a look at this, as this breaks functionality.
Can someone confirm this ?

**Comment by hosuaby** [comment] 2020-01-27 15:43
This code was added to work with cluster plugin. Do you use any other Leaflet plugins ?

**Comment by elvisef** [comment] 2020-01-31 11:51
Nope, only this one.

**Comment by hosuaby** [comment] 2020-02-22 11:11
Please, check if thide demo is working: http://hosuaby.github.io/Leaflet.SmoothMarkerBouncing/

**Comment by hosuaby** [comment] 2020-09-05 19:36
Currently, this problem is confirmed only in case of plugin used on old (non 3D-enabled) browser.

**Comment by hosuaby** [comment] 2020-11-03 10:52
Problem is not relevant for v2.0.1 because this code no longer exists. I will close this issue. If it re-appers it will be reopened.

**Closed by hosuaby** 2020-11-03 10:52 UTC
